from bing_image_downloader import downloader

downloader.download('Jawaharlal Nehru', limit=100,  output_dir='datanew', adult_filter_off=True, force_replace=False, timeout=220, verbose=True)
downloader.download('Lal Bahadur Shastri', limit=100,  output_dir='datanew', adult_filter_off=True, force_replace=False, timeout=220, verbose=True)
downloader.download('Indira Gandhi', limit=100,  output_dir='datanew', adult_filter_off=True, force_replace=False, timeout=220, verbose=True)
downloader.download('Rajiv Gandhi', limit=100,  output_dir='datanew', adult_filter_off=True, force_replace=False, timeout=220, verbose=True)
downloader.download('Manmohan Singh', limit=100,  output_dir='datanew', adult_filter_off=True, force_replace=False, timeout=220, verbose=True)
downloader.download('Narendra Modi', limit=100,  output_dir='datanew', adult_filter_off=True, force_replace=False, timeout=220, verbose=True)
downloader.download('Atal Bihari Vajpayee', limit=100,  output_dir='datanew', adult_filter_off=True, force_replace=False, timeout=220, verbose=True)
downloader.download('Amit Shah', limit=100,  output_dir='datanew', adult_filter_off=True, force_replace=False, timeout=220, verbose=True)
downloader.download('Mohan Bhagwat', limit=100,  output_dir='datanew', adult_filter_off=True, force_replace=False, timeout=220, verbose=True)
downloader.download('Arun Jaitley', limit=100,  output_dir='datanew', adult_filter_off=True, force_replace=False, timeout=220, verbose=True)
downloader.download('Nitin Gadkari', limit=100,  output_dir='datanew', adult_filter_off=True, force_replace=False, timeout=220, verbose=True)
downloader.download('Nitish Kumar', limit=100,  output_dir='datanew', adult_filter_off=True, force_replace=False, timeout=220, verbose=True)
downloader.download('Mamata Banerjee', limit=100,  output_dir='datanew', adult_filter_off=True, force_replace=False, timeout=220, verbose=True)
downloader.download('Yogi Adityanath', limit=100,  output_dir='datanew', adult_filter_off=True, force_replace=False, timeout=220, verbose=True)
downloader.download('Rahul Gandhi', limit=100,  output_dir='datanew', adult_filter_off=True, force_replace=False, timeout=220, verbose=True)
downloader.download('Arvind Kejriwal', limit=100,  output_dir='datanew', adult_filter_off=True, force_replace=False, timeout=220, verbose=True)
downloader.download('Sonia Gandhi', limit=100,  output_dir='datanew', adult_filter_off=True, force_replace=False, timeout=220, verbose=True)
downloader.download('Mamta Banerjee', limit=100,  output_dir='datanew', adult_filter_off=True, force_replace=False, timeout=220, verbose=True)
